AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Description: >-
  Customer master keys used throughout the data platform if encryption is
  enabled.

Outputs:

  UserPoolArn:
    Description: The data platform Cognito user pool ARN.
    Value: !GetAtt UserPool.Arn
    Export:
      Name: UserPoolArn

  UserPoolId:
    Description: The data platform Cognito user pool id.
    Value: !Ref UserPool
    Export:
      Name: UserPoolId

Resources:

  #
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: data_platform-user_pool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: True

  #
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: data_platform-user_pool-client
      UserPoolId: !Ref UserPool
      GenerateSecret: True
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
