AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Description: >-
  Deploy S3 buckets, and a CloudTrail trail to event off S3 events.

Resources:

  CatalogWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: catalog
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 500000000
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation:
            Fn::Join:
              - ""
              - - "s3://user-scratch-space-"
                - !Ref EnvironmentName
