AWSTemplateFormatVersion: "2010-09-09"

Transform:
  - AWS::Serverless-2016-10-31

Description: >-
  Lambda layers containing custom Python libraries and other shared
  dependencies.

Outputs:

  EventsPythonUtilsLayerArn:
    Description: >-
      Lambda LayerVersion ARN. Contains handlers and utilities to use
      Eventbridge events with AWS Lambdas.
    Value:
      Fn::Join:
        - ""
        - - "arn:"
          - !Ref AWS::Partition
          - ":logs:"
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":layer:python-events_utils"
    Export:
      Name: EventsPythonUtilsLayerVersion

  EventsPythonUtilsLayerVersion:
    Description: >-
      Latest Lambda LayerVersion number for the python-events_utils.
      Only indicative, do not import!
    Value:
      Fn::Select:
          - 7
          - Fn::Split:
              - ":"
              - !Ref EventsPythonUtilsLayerVersion
    Export:
      Name: EventsPythonUtilsLayerVersionNumber

  SqsPythonUtilsLayerArn:
    Description: >-
      Lambda LayerVersion ARN. Contains Python handlers and utilities to use
      SQS Queues with AWS Lambdas.
    Value:
      Fn::Join:
        - ""
        - - "arn:"
          - !Ref AWS::Partition
          - ":logs:"
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":layer:python-sqs_utils"
    Export:
      Name: SqsPythonUtilsLayerArn

  SqsPythonUtilsLayerVersion:
    Description: >-
      Latest Lambda LayerVersion number for the python-sqs_utils.
      Only indicative, do not import!
    Value:
      Fn::Select:
          - 7
          - Fn::Split:
              - ":"
              - !Ref SqsPythonUtilsLayerVersion
    Export:
      Name: SqsPythonUtilsLayerVersionNumber

Resources:

  EventsPythonUtilsLayerVersion:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: python-events_utils
        Description: >-
          Python handlers and utilities to use Eventbridge events with AWS
          Lambdas.
        ContentUri: events_utils/
        CompatibleRuntimes:
          - python3.8
        LicenseInfo: MIT
      Metadata:
        BuildMethod: python3.8

  SqsPythonUtilsLayerVersion:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: python-sqs_utils
        Description: >-
          Python handlers and utilities to use SQS Queues with AWS Lambdas.
        ContentUri: sqs_utils/
        CompatibleRuntimes:
          - python3.8
        LicenseInfo: MIT
      Metadata:
        BuildMethod: python3.8
